// <auto-generated />
using System;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DB.Migrations
{
    [DbContext(typeof(RRCoderDBContext))]
    [Migration("20190323145624_Init1")]
    partial class Init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rrCoder")
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Bemerkung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Betreff");

                    b.Property<int?>("CodeContentId");

                    b.Property<DateTime>("Erstellt_Datum");

                    b.Property<int?>("Erstellt_UserId");

                    b.Property<DateTime?>("Geaendert_Datum");

                    b.Property<int?>("Geaendert_UserId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("CodeContentId");

                    b.HasIndex("Erstellt_UserId");

                    b.HasIndex("Geaendert_UserId");

                    b.ToTable("Bemerkung");
                });

            modelBuilder.Entity("Entities.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<string>("Username");

                    b.Property<string>("Vorname");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Entities.CodeContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Betreff");

                    b.Property<DateTime>("Erstellt_Datum");

                    b.Property<int?>("Erstellt_UserId");

                    b.Property<DateTime?>("Geaendert_Datum");

                    b.Property<int?>("Geaendert_UserId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("Erstellt_UserId");

                    b.HasIndex("Geaendert_UserId");

                    b.ToTable("CodeContent");
                });

            modelBuilder.Entity("Entities.Bemerkung", b =>
                {
                    b.HasOne("Entities.CodeContent", "CodeContent")
                        .WithMany("Bemerkungen")
                        .HasForeignKey("CodeContentId");

                    b.HasOne("Entities.Benutzer", "Erstellt_User")
                        .WithMany("Erstellt_Bemerkung")
                        .HasForeignKey("Erstellt_UserId");

                    b.HasOne("Entities.Benutzer", "Geaendert_User")
                        .WithMany("Geaenderte_Bemerkung")
                        .HasForeignKey("Geaendert_UserId");
                });

            modelBuilder.Entity("Entities.CodeContent", b =>
                {
                    b.HasOne("Entities.Benutzer", "Erstellt_User")
                        .WithMany("Erstellt_CodeContent")
                        .HasForeignKey("Erstellt_UserId");

                    b.HasOne("Entities.Benutzer", "Geaendert_User")
                        .WithMany("Geaenderte_CodeContent")
                        .HasForeignKey("Geaendert_UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
